status = error
name = MedallionProjectLog4j2Config

appender.console.type = Console
appender.console.name = console
appender.console.target = SYSTEM_ERR
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{HH:mm:ss} %-5p %c{1}: %m%n

rootLogger.level = error
rootLogger.appenderRefs = console
rootLogger.appenderRef.console.ref = console

logger.spark.name = org.apache.spark
logger.spark.level = error

logger.hadoop.name = org.apache.hadoop
logger.hadoop.level = error

logger.delta.name = io.delta
logger.delta.level = error

logger.shutdownhook.name = org.apache.spark.util.ShutdownHookManager
logger.shutdownhook.level = off

logger.sparkenv.name = org.apache.spark.SparkEnv
logger.sparkenv.level = off